### PR TITLE
fix: request limit

### LINKED ISSUE #189: fix: rate limit
For users with multiple (many) txs they hit the rate limit of 10 requests/s for each IP.  We need to implement a way to replace fetch with something that has a rate limit to queue the requests, with minimal changes.

### PR DESCRIPTION
**Pull request by LuizAsFight**
Features
- Create a provider for the bridge to use the same instance everywhere
- Apply a rate limiter to this provider

side effects
- Fix all places to use the correct provider
- Override the `useBalance` hook from `@fuels-wallet/react` package, to be able to use bridge provider

Closes #189

### CODE REVIEW

File: packages/app/src/systems/Chains/fuel/utils/provider.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
+import type { FetchRequestOptions } from 'fuels';
+import { Provider } from 'fuels';
+
+let requestTimestamps: number[] = [];
+const maxRequestsPerSecond = 10;
```
Comment (luizstacio) [inline packages/app/src/systems/Chains/fuel/utils/provider.ts:5]: we can increase right now the limit is 30

**Review by luizstacio — CHANGES_REQUESTED** [review]

File: packages/app/src/systems/Chains/fuel/utils/provider.ts (hunk 1 above)
Comment (LuizAsFight) [reply packages/app/src/systems/Chains/fuel/utils/provider.ts:5]: I'll increase to 20 as I want to have some room because the wallet uses its own provider and can do requests out of created provider scope

**Review by luizstacio — APPROVED** [review]
